[workspace]
members = [
    "crates/client",
    "crates/migrations",
    "crates/reindexer",
    "crates/shared",
    "crates/spyglass",
    "crates/tauri",
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"